CREATE DATABASE IF NOT EXISTS physio_clinic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE physio_clinic;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    role ENUM('admin_doctor','sub_doctor','receptionist','patient') NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    security_question VARCHAR(255) NOT NULL,
    security_answer_hash VARCHAR(255) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    can_view_reports TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE patients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NULL,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    age INT NULL,
    gender VARCHAR(20),
    dob DATE NULL,
    occupation VARCHAR(120),
    assessment_date DATE NULL,
    dominance VARCHAR(50),
    condition_duration VARCHAR(100),
    phone VARCHAR(40),
    address VARCHAR(255),
    emergency_contact VARCHAR(120),
    chief_complain TEXT,
    history_present_illness TEXT,
    past_medical_history TEXT,
    surgical_history TEXT,
    family_history TEXT,
    socio_economic_status TEXT,
    observation_built TEXT,
    observation_attitude_limb TEXT,
    observation_posture TEXT,
    observation_deformity TEXT,
    aids_applications TEXT,
    gait TEXT,
    palpation_tenderness TEXT,
    palpation_oedema VARCHAR(50),
    palpation_warmth TEXT,
    palpation_crepitus TEXT,
    examination_rom TEXT,
    muscle_power TEXT,
    muscle_bulk TEXT,
    ligament_instability TEXT,
    pain_type TEXT,
    pain_site TEXT,
    pain_nature TEXT,
    pain_aggravating_factor TEXT,
    pain_relieving_factor TEXT,
    pain_measurement TINYINT NULL,
    gait_assessment TEXT,
    diagnosis TEXT,
    treatment_goals TEXT,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE patient_visits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    visit_date DATE NOT NULL,
    chief_complain TEXT,
    history_present_illness TEXT,
    past_medical_history TEXT,
    surgical_history TEXT,
    family_history TEXT,
    socio_economic_status TEXT,
    observation_built TEXT,
    observation_attitude_limb TEXT,
    observation_posture TEXT,
    observation_deformity TEXT,
    aids_applications TEXT,
    gait TEXT,
    palpation_tenderness TEXT,
    palpation_oedema VARCHAR(50),
    palpation_warmth TEXT,
    palpation_crepitus TEXT,
    examination_rom TEXT,
    muscle_power TEXT,
    muscle_bulk TEXT,
    ligament_instability TEXT,
    pain_type TEXT,
    pain_site TEXT,
    pain_nature TEXT,
    pain_aggravating_factor TEXT,
    pain_relieving_factor TEXT,
    pain_measurement TINYINT NULL,
    gait_assessment TEXT,
    diagnosis TEXT,
    treatment_goals TEXT,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

CREATE TABLE treatment_plans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    visit_id INT NULL,
    total_sessions INT NOT NULL,
    start_date DATE,
    status VARCHAR(30) DEFAULT 'active',
    notes TEXT,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (visit_id) REFERENCES patient_visits(id) ON DELETE SET NULL
);

CREATE TABLE sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    treatment_plan_id INT NOT NULL,
    visit_id INT NULL,
    session_date DATE NOT NULL,
    attendance ENUM('attended','missed','cancelled') DEFAULT 'attended',
    notes TEXT,
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (treatment_plan_id) REFERENCES treatment_plans(id) ON DELETE CASCADE,
    FOREIGN KEY (visit_id) REFERENCES patient_visits(id) ON DELETE SET NULL
);

CREATE TABLE payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    visit_id INT NULL,
    amount DECIMAL(10,2) NOT NULL,
    payment_date DATE NOT NULL,
    method VARCHAR(50),
    notes TEXT,
    receipt_no VARCHAR(50),
    created_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (visit_id) REFERENCES patient_visits(id) ON DELETE SET NULL
);

CREATE TABLE patient_documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    uploaded_by INT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
);

CREATE TABLE patient_assignments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    sub_doctor_id INT NOT NULL,
    assigned_by INT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (sub_doctor_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE pain_master (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(80) NOT NULL,
    subcategory VARCHAR(120) NOT NULL,
    is_other TINYINT(1) NOT NULL DEFAULT 0,
    active TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE patient_pain (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id INT NOT NULL,
    visit_id INT NOT NULL,
    pain_master_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    FOREIGN KEY (visit_id) REFERENCES patient_visits(id) ON DELETE CASCADE,
    FOREIGN KEY (pain_master_id) REFERENCES pain_master(id) ON DELETE CASCADE
);

INSERT INTO pain_master (category, subcategory, is_other) VALUES
('Shoulder','Rotator cuff injuries',0),
('Shoulder','Frozen shoulder',0),
('Shoulder','Shoulder arthritis',0),
('Shoulder','Instability and dislocation',0),
('Shoulder','Impingement syndrome',0),
('Shoulder','Bursitis',0),
('Shoulder','Tendon issues',0),
('Shoulder','Fracture',0),
('Shoulder','Other',1),
('Neck','Cervical spondylosis',0),
('Neck','Herniated / bulging disc',0),
('Neck','Cervical spinal stenosis',0),
('Neck','Cervical myelopathy',0),
('Neck','Degenerative disc disease',0),
('Neck','Spondylolisthesis',0),
('Neck','Other',1),
('Elbow','Tennis elbow',0),
('Elbow','Golfer''s elbow',0),
('Elbow','Olecranon bursitis',0),
('Elbow','Osteoarthritis',0),
('Elbow','Rheumatoid arthritis',0),
('Elbow','Nerve compression',0),
('Elbow','Trauma & fracture',0),
('Elbow','Ligament injury',0),
('Elbow','Other',1),
('Hand','Carpal tunnel syndrome',0),
('Hand','Arthritis',0),
('Hand','Trigger finger',0),
('Hand','De Quervain''s tenosynovitis',0),
('Hand','Tendinitis',0),
('Hand','Dupuytren''s contracture',0),
('Hand','Swan-neck deformity',0),
('Hand','Boutonniere deformity',0),
('Hand','Cysts & tumors',0),
('Hand','Injuries',0),
('Hand','Other',1),
('Back','Herniated disc',0),
('Back','Spinal stenosis',0),
('Back','Cauda equina syndrome',0),
('Back','Spondylosis',0),
('Back','Spondylolisthesis',0),
('Back','Scoliosis / kyphosis',0),
('Back','Muscle strain / ligament sprain',0),
('Back','Osteoporosis & compression',0),
('Back','Ankylosing spondylitis',0),
('Back','Spinal tumor',0),
('Back','Infection',0),
('Back','Other',1),
('Hip','Arthritis',0),
('Hip','Avascular necrosis (AVN)',0),
('Hip','Hip dysplasia (congenital misalignment)',0),
('Hip','Femoroacetabular impingement',0),
('Hip','Osteoporosis',0),
('Hip','Infection',0),
('Hip','Bone cancer',0),
('Hip','Fracture',0),
('Hip','Bursitis',0),
('Hip','Labral tear',0),
('Hip','Tendinitis',0),
('Hip','Muscle strain',0),
('Hip','Piriformis syndrome',0),
('Hip','Other',1),
('Knee','Arthritis',0),
('Knee','Ligament injury (ACL/PCL/MCL/LCL)',0),
('Knee','Meniscus tear',0),
('Knee','Tendinitis',0),
('Knee','Bursitis & cysts',0),
('Knee','Patellofemoral pain syndrome',0),
('Knee','Fracture',0),
('Knee','Other',1),
('Ankle & Foot','Ankle sprain',0),
('Ankle & Foot','Fracture',0),
('Ankle & Foot','Osteoarthritis',0),
('Ankle & Foot','Tendon injury',0),
('Ankle & Foot','Gout',0),
('Ankle & Foot','Tarsal tunnel syndrome',0),
('Ankle & Foot','Other',1);
